; Etch and overgrow 2026, stretched honeycomb (Kekule) lattices, pump-blueshift edge states
; generated by pattern_creator/projects/eno_run_2026/stretched_honeycomb.py
; target etch depth 18 meV; pillar diameter 2050 nm for all lattices
; 4 x 4 grid: columns v = 1.100 / 1.133 / 1.167 / 1.200, rows stretch s = 0 / 80 / 110 / 140 nm
; units nm; exposed area = pillar mesas; 25 nm raster, I 16, C 100 (as 2024 EnO lattices)
; lattices: generate_pattern.Lattice (bulk _x_0_y_0 with D-line repetition + edge/corner structures),
; trimmed so that no area is exposed twice; parameters in shc_field_devices.csv
; grid 3 x 2 fields, pitch 550 x 550 um, field x/y index labels from numbers_shc.pat

current = 25000

origin = 0, 0
x = 0
y = 0
stage

for m = 1 to 2
x = 0
for n = 1 to 3
stage

sfile = shc_field
draw(shc_field_f0_kek_v1p100_s000_x_0_y_0)
draw(shc_field_f0_kek_v1p100_s000_x_0_y_1)
draw(shc_field_f0_kek_v1p100_s000_x_0_y_-1)
draw(shc_field_f0_kek_v1p133_s000_x_0_y_0)
draw(shc_field_f0_kek_v1p133_s000_x_0_y_1)
draw(shc_field_f0_kek_v1p133_s000_x_0_y_-1)
draw(shc_field_f0_kek_v1p167_s000_x_0_y_0)
draw(shc_field_f0_kek_v1p167_s000_x_0_y_1)
draw(shc_field_f0_kek_v1p167_s000_x_0_y_-1)
draw(shc_field_f0_kek_v1p200_s000_x_0_y_0)
draw(shc_field_f0_kek_v1p200_s000_x_0_y_1)
draw(shc_field_f0_kek_v1p200_s000_x_0_y_-1)
draw(shc_field_f0_kek_v1p100_s080_x_0_y_0)
draw(shc_field_f0_kek_v1p100_s080_x_0_y_1)
draw(shc_field_f0_kek_v1p100_s080_x_0_y_-1)
draw(shc_field_f0_kek_v1p133_s080_x_0_y_0)
draw(shc_field_f0_kek_v1p133_s080_x_0_y_1)
draw(shc_field_f0_kek_v1p133_s080_x_0_y_-1)
draw(shc_field_f0_kek_v1p167_s080_x_0_y_0)
draw(shc_field_f0_kek_v1p167_s080_x_0_y_1)
draw(shc_field_f0_kek_v1p167_s080_x_0_y_-1)
draw(shc_field_f0_kek_v1p200_s080_x_0_y_0)
draw(shc_field_f0_kek_v1p200_s080_x_0_y_1)
draw(shc_field_f0_kek_v1p200_s080_x_0_y_-1)
draw(shc_field_f0_kek_v1p100_s110_x_0_y_0)
draw(shc_field_f0_kek_v1p100_s110_x_1_y_0)
draw(shc_field_f0_kek_v1p100_s110_x_0_y_1)
draw(shc_field_f0_kek_v1p100_s110_x_0_y_-1)
draw(shc_field_f0_kek_v1p100_s110_x_-1_y_0)
draw(shc_field_f0_kek_v1p133_s110_x_0_y_0)
draw(shc_field_f0_kek_v1p133_s110_x_0_y_1)
draw(shc_field_f0_kek_v1p133_s110_x_0_y_-1)
draw(shc_field_f0_kek_v1p167_s110_x_0_y_0)
draw(shc_field_f0_kek_v1p167_s110_x_0_y_1)
draw(shc_field_f0_kek_v1p167_s110_x_0_y_-1)
draw(shc_field_f0_kek_v1p200_s110_x_0_y_0)
draw(shc_field_f0_kek_v1p200_s110_x_0_y_1)
draw(shc_field_f0_kek_v1p200_s110_x_0_y_-1)
draw(shc_field_f0_kek_v1p100_s140_x_0_y_0)
draw(shc_field_f0_kek_v1p100_s140_x_1_y_0)
draw(shc_field_f0_kek_v1p100_s140_x_0_y_1)
draw(shc_field_f0_kek_v1p100_s140_x_0_y_-1)
draw(shc_field_f0_kek_v1p100_s140_x_-1_y_0)
draw(shc_field_f0_kek_v1p133_s140_x_0_y_0)
draw(shc_field_f0_kek_v1p133_s140_x_1_y_0)
draw(shc_field_f0_kek_v1p133_s140_x_0_y_1)
draw(shc_field_f0_kek_v1p133_s140_x_0_y_-1)
draw(shc_field_f0_kek_v1p133_s140_x_-1_y_0)
draw(shc_field_f0_kek_v1p167_s140_x_0_y_0)
draw(shc_field_f0_kek_v1p167_s140_x_0_y_1)
draw(shc_field_f0_kek_v1p167_s140_x_0_y_-1)
draw(shc_field_f0_kek_v1p200_s140_x_0_y_0)
draw(shc_field_f0_kek_v1p200_s140_x_0_y_1)
draw(shc_field_f0_kek_v1p200_s140_x_0_y_-1)
draw(shc_field_f0_ref_overlap_dimers_2024)
draw(shc_field_f0_ref_mesa_50um_2024)
draw(shc_field_f0_ref_arrows_right)
draw(shc_field_f0_ref_arrows_up)
draw(shc_field_f0_labels)

sfile = numbers_shc
idraw(nbr_x_, n)
idraw(nbr_y_, m)

+x = 550
next n
+y = 550
next m

END
