; Etch and overgrow 2026, stretched honeycomb (Kekule) lattices, pump-blueshift edge states
; generated by pattern_creator/projects/eno_run_2026/stretched_honeycomb.py
; target etch depth 18 meV; GPE sets #1 (17.50 meV) and #3 (18.80 meV) from gpe_v3.py
; per set: stretch 0/50/80/100/120 % of s_opt, diameter -80/-40/+40 nm, overlap v -+0.03
; units nm; exposed area = pillar mesas; lattices on 10 nm raster, I 16, C 100 (as 2024 EnO lattices)
; lattices: generate_pattern.Lattice (bulk _x_0_y_0 with D-line repetition + edge/corner structures),
; trimmed so that no area is exposed twice; parameters in shc_field_devices.csv

current = 25000
origin = 0, 0

sfile = shc_field

; ===== write field 0
x = 0
y = 0
stage
draw(shc_field_f0_kek_set3_s000_x_0_y_0)
draw(shc_field_f0_kek_set3_s000_x_0_y_1)
draw(shc_field_f0_kek_set3_s000_x_0_y_-1)
draw(shc_field_f0_kek_set3_s050_x_0_y_0)
draw(shc_field_f0_kek_set3_s050_x_0_y_1)
draw(shc_field_f0_kek_set3_s050_x_0_y_-1)
draw(shc_field_f0_kek_set3_s080_x_0_y_0)
draw(shc_field_f0_kek_set3_s080_x_0_y_1)
draw(shc_field_f0_kek_set3_s080_x_0_y_-1)
draw(shc_field_f0_kek_set3_s100_x_0_y_0)
draw(shc_field_f0_kek_set3_s100_x_0_y_1)
draw(shc_field_f0_kek_set3_s100_x_0_y_-1)
draw(shc_field_f0_kek_set3_s120_x_0_y_0)
draw(shc_field_f0_kek_set3_s120_x_0_y_1)
draw(shc_field_f0_kek_set3_s120_x_0_y_-1)
draw(shc_field_f0_kek_set3_ddm80_x_0_y_0)
draw(shc_field_f0_kek_set3_ddm80_x_0_y_1)
draw(shc_field_f0_kek_set3_ddm80_x_0_y_-1)
draw(shc_field_f0_kek_set3_ddm40_x_0_y_0)
draw(shc_field_f0_kek_set3_ddm40_x_0_y_1)
draw(shc_field_f0_kek_set3_ddm40_x_0_y_-1)
draw(shc_field_f0_kek_set3_ddp40_x_0_y_0)
draw(shc_field_f0_kek_set3_ddp40_x_0_y_1)
draw(shc_field_f0_kek_set3_ddp40_x_0_y_-1)
draw(shc_field_f0_kek_set3_v1p151_x_0_y_0)
draw(shc_field_f0_kek_set3_v1p151_x_0_y_1)
draw(shc_field_f0_kek_set3_v1p151_x_0_y_-1)
draw(shc_field_f0_kek_set3_v1p211_x_0_y_0)
draw(shc_field_f0_kek_set3_v1p211_x_0_y_1)
draw(shc_field_f0_kek_set3_v1p211_x_0_y_-1)
draw(shc_field_f0_kek_set1_s000_x_0_y_0)
draw(shc_field_f0_kek_set1_s000_x_0_y_1)
draw(shc_field_f0_kek_set1_s000_x_0_y_-1)
draw(shc_field_f0_kek_set1_s050_x_0_y_0)
draw(shc_field_f0_kek_set1_s050_x_0_y_1)
draw(shc_field_f0_kek_set1_s050_x_0_y_-1)
draw(shc_field_f0_kek_set1_s080_x_0_y_0)
draw(shc_field_f0_kek_set1_s080_x_0_y_1)
draw(shc_field_f0_kek_set1_s080_x_0_y_-1)
draw(shc_field_f0_kek_set1_s100_x_0_y_0)
draw(shc_field_f0_kek_set1_s100_x_0_y_1)
draw(shc_field_f0_kek_set1_s100_x_0_y_-1)
draw(shc_field_f0_kek_set1_s120_x_0_y_0)
draw(shc_field_f0_kek_set1_s120_x_1_y_0)
draw(shc_field_f0_kek_set1_s120_x_0_y_1)
draw(shc_field_f0_kek_set1_s120_x_0_y_-1)
draw(shc_field_f0_kek_set1_s120_x_-1_y_0)
draw(shc_field_f0_kek_set1_ddm80_x_0_y_0)
draw(shc_field_f0_kek_set1_ddm80_x_0_y_1)
draw(shc_field_f0_kek_set1_ddm80_x_0_y_-1)
draw(shc_field_f0_kek_set1_ddm40_x_0_y_0)
draw(shc_field_f0_kek_set1_ddm40_x_0_y_1)
draw(shc_field_f0_kek_set1_ddm40_x_0_y_-1)
draw(shc_field_f0_kek_set1_ddp40_x_0_y_0)
draw(shc_field_f0_kek_set1_ddp40_x_1_y_0)
draw(shc_field_f0_kek_set1_ddp40_x_0_y_1)
draw(shc_field_f0_kek_set1_ddp40_x_0_y_-1)
draw(shc_field_f0_kek_set1_ddp40_x_-1_y_0)
draw(shc_field_f0_kek_set1_v1p088_x_0_y_0)
draw(shc_field_f0_kek_set1_v1p088_x_1_y_0)
draw(shc_field_f0_kek_set1_v1p088_x_0_y_1)
draw(shc_field_f0_kek_set1_v1p088_x_0_y_-1)
draw(shc_field_f0_kek_set1_v1p088_x_-1_y_0)
draw(shc_field_f0_kek_set1_v1p148_x_0_y_0)
draw(shc_field_f0_kek_set1_v1p148_x_0_y_1)
draw(shc_field_f0_kek_set1_v1p148_x_0_y_-1)
draw(shc_field_f0_ref_overlap_series_2024)
draw(shc_field_f0_labels)

END
